apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: istio-system
data:
  prometheus.rules.yml: |-
    groups:
    - name: prysm
      rules:
      - alert: stalled_chain
        expr: delta(avg(state_last_slot > scalar(max(state_last_slot) - 100))[10m:30s]) < 50
        for: 1m
        annotations:
          summary: No block slots advanced in 2 minutes
      - alert: too_long_since_finality_10
        expr: max(state_last_slot / 8) - floor(max(state_last_finalized_epoch)) > 10
        for: 1m
        annotations:
          summary: No finality in 10 epochs
      - alert: too_long_since_finality_25
        expr: max(state_last_slot / 8) - floor(max(state_last_finalized_epoch)) > 25
        for: 1m
        annotations:
          summary: No finality in 25 epochs
      - alert: too_long_since_finality_100
        expr: max(state_last_slot / 8) - floor(max(state_last_finalized_epoch)) > 100
        for: 1m
        annotations:
          summary: No finality in 100 epochs
      - alert: high_reorg_rate
        expr: max(delta(reorg_counter[10m])) > 5
        for: 1m
        annotations:
          summary: Some nodes are seeing more than 5 reorgs in 10 minutes
      - alert: high_goroutines
        expr: max_over_time(go_goroutines{component="beacon-chain"}[1m]) > 2000
        for: 1m
        annotations:
          summary: Pod {{ $labels.pod_name}} experencing more than 2000 goroutines
          description: "{{ $labels.pod_name }} has {{ $value }} goroutines"
      - alert: low_disk_space_1gb
        expr: kubelet_volume_stats_available_bytes < 1e9
        for: 1m
        annotations:
          summary: Pod has less than 1GB free disk space in their persistent disk.
      - alert: balance_too_low
        expr: eth_balance < 200
        for: 1m
        annotations:
          summary: ETH1 wallet has less than 200 ETH
          description: "{{ $labels.name }} ({{ $labels.address }}) has {{ $value }} ETH"
      - alert: high_grpc_beacon_chain_error_rate
        expr: sum(rate(istio_requests_total{reporter="destination",destination_service=~"beacon-chain.beacon-chain.svc.cluster.local",response_code!~"5.*"}[5m])) / sum(rate(istio_requests_total{reporter="destination",destination_service=~"beacon-chain.beacon-chain.svc.cluster.local"}[5m])) < 0.99
        for: 1m
        annotations:
          summary: Beacon node global success rate is less than 99%.
          description: Success rate = {{ $value }}
      - alert: high_grpc_beacon_chain_method_error_rate
        expr: sum(rate(grpc_server_handled_total{component="beacon-chain",grpc_code="OK"}[5m]))  by (grpc_method) / sum(rate(grpc_server_handled_total{component="beacon-chain"}[5m])) by (grpc_method) < 0.95
        for: 1m
        annotations:
          summary: Beacon chain gRPC method success rate is less than 95%.
          description: "{{ $labels.grpc_method }} {{ $value }}"