kind: Service
apiVersion: v1
metadata:
  name: geth-ethstats
  namespace: pow
spec:
  selector:
    component: ethstats
    universe: geth
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
