apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: pow
  annotations:
    nginx.org/websocket-services: "geth-ethstats"
spec:
  rules:
  - host: ethstats.prylabs.network
    http:
      paths:
      - path: /
        backend:
          serviceName: geth-ethstats
          servicePort: 3000
  - host: powexplorer.prylabs.network
    http:
      paths:
      - path: /
        backend:
          serviceName: blockscout
          servicePort: 4000
  - host: powfaucet.prylabs.network
    http: 
      paths: 
      - path: /
        backend:
          serviceName: geth-faucet
          servicePort: 8080
  - host: powchain.prylabs.network
    http:
      paths: 
        - paths:
          backend:
            serviceName: geth-nodes
            servicePort: 8545
