kind: Service
apiVersion: v1
metadata:
  name: geth-nodes
  namespace: pow
spec:
  selector:
    component: node
    universe: geth
  ports:
    - port: 8545
      targetPort: 8545
      name: rpc
      protocol: TCP
    - port: 8546
      targetPort: 8546
      name: ws
      protocol: TCP
  type: LoadBalancer
