name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ ubuntu-18.04, macos-11 ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Cache bazelisk download
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazelisk
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ matrix.os }}-${{ env.cache-name }}-development

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build beacon-chain client
        run: |
          bazel build //beacon-chain
          mv ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain ./bazel-bin/cmd/beacon-chain/beacon-chain_/vanguard-Linux-x86_64

      - name: Build validator
        run: |
          bazel build //validator
          mv ./bazel-bin/cmd/validator/validator_/validator ./bazel-bin/cmd/validator/validator_/lukso-validator-Linux-x86_64

      - name: Run beacon-chain for Darwin
        if: matrix.platform == 'macos-11'
        run: |
          bazel build //beacon-chain:beacon-chain
          mv ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain ./bazel-bin/cmd/beacon-chain/beacon-chain_/vanguard-Darwin-x86_64

      - name: Run validator for Darwin
        if: matrix.platform == 'macos-11'
        run: |
          bazel build //validator:validator
          mv ./bazel-bin/cmd/validator/validator_/validator ./bazel-bin/cmd/validator/validator_/lukso-validator-Darwin-x86_64

      - name: Run beacon-chain for Windows
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          bazel build //beacon-chain:beacon-chain --config=windows_amd64_docker
          mv ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain.exe ./bazel-bin/cmd/beacon-chain/beacon-chain_/vanguard-Windows-x86_64.exe

      - name: Run validator for Windows
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          bazel build //validator:validator --config=windows_amd64_docker
          mv ./bazel-bin/cmd/validator/validator_/validator.exe ./bazel-bin/cmd/validator/validator_/lukso-validator-Windows-x86_64.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release
          draft: false
          files: |
            ./bazel-bin/cmd/beacon-chain/beacon-chain_/vanguard-*
            ./bazel-bin/cmd/validator/validator_/lukso-validator-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}